import './globals.css'
import { Inter } from 'next/font/google'
import '@smastrom/react-rating/style.css'
import Prvider from '@/Redux/provider'
import Navbar from './Nabar/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Navbar />
        <Prvider>
          {children}
        </Prvider>
      </body>
    </html>
  )
}
